<?xml version="1.0" encoding="utf-8"?><Database Name="NetworkMarketing" Class="NetworkMarketingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TE3A2ID\SQLEXPRESS;Initial Catalog=NetworkMarketing;Persist Security Info=True;User ID=NetworkMarketing" SettingsObjectName="NetworkDataAccess.Properties.Settings" SettingsPropertyName="NetworkMarketingConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ClassUser" Member="ClassUsers">
    <Type Name="ClassUser">
      <Column Name="ClassUserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_ClassUser" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="Class_ClassUser" Member="Class" ThisKey="ClassID" OtherKey="ClassID" Type="Class" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EVouchers" Member="EVouchers">
    <Type Name="EVoucher">
      <Column Name="EVouchersID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreaterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UsedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VoucherCode" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UsedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_EVoucher" Member="Creator" Storage="_User" ThisKey="CreaterID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_EVoucher1" Member="User" Storage="_User1" ThisKey="UsedBy" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transactions" Member="Transactions">
    <Type Name="Transaction">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RecieverID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Transaction" Member="Sender" Storage="_User" ThisKey="SenderID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_Transaction1" Member="Reciever" Storage="_User1" ThisKey="RecieverID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TransctionKey" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Country" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SponserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageExt" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_ClassUser" Member="ClassUsers" ThisKey="UserID" OtherKey="UserID" Type="ClassUser" />
      <Association Name="User_EVoucher" Member="EVouchers" ThisKey="UserID" OtherKey="CreaterID" Type="EVoucher" />
      <Association Name="User_EVoucher1" Member="UsedEVouchers" Storage="_EVouchers1" ThisKey="UserID" OtherKey="UsedBy" Type="EVoucher" />
      <Association Name="User_Transaction" Member="SentTransactions" Storage="_Transactions" ThisKey="UserID" OtherKey="SenderID" Type="Transaction" />
      <Association Name="User_Transaction1" Member="RecievedTransactions" Storage="_Transactions1" ThisKey="UserID" OtherKey="RecieverID" Type="Transaction" />
      <Association Name="User_User" Member="Childrens" Storage="_Users" ThisKey="UserID" OtherKey="CreatedBy" Type="User" />
      <Association Name="User_User1" Member="Followers" Storage="_Users1" ThisKey="UserID" OtherKey="SponserID" Type="User" />
      <Association Name="User_BankDetail" Member="BankDetails" ThisKey="UserID" OtherKey="UserID" Type="BankDetail" />
      <Association Name="User_LeaderFollower" Member="LeaderFollowers" ThisKey="UserID" OtherKey="LeaderID" Type="LeaderFollower" />
      <Association Name="User_LeaderFollower1" Member="RealFollowers" ThisKey="UserID" OtherKey="FollowerID" Type="LeaderFollower" />
      <Association Name="User_User" Member="Creater" Storage="_User1" ThisKey="CreatedBy" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_User1" Member="Sponser" Storage="_User2" ThisKey="SponserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Classes" Member="Classes">
    <Type Name="Class">
      <Column Name="ClassID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClassCreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ClassBrokenDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ClassType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Class_ClassUser" Member="ClassUsers" ThisKey="ClassID" OtherKey="ClassID" Type="ClassUser" />
      <Association Name="Class_LeaderFollower" Member="LeaderFollowers" ThisKey="ClassID" OtherKey="LeaderClassID" Type="LeaderFollower" />
    </Type>
  </Table>
  <Table Name="dbo.BankDetails" Member="BankDetails">
    <Type Name="BankDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TransferType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountNumber" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="User_BankDetail" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LeaderFollower" Member="LeaderFollowers">
    <Type Name="LeaderFollower">
      <Column Name="LeaderFollowerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LeaderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FollowerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeaderClassID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FollowedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Class_LeaderFollower" Member="Class" ThisKey="LeaderClassID" OtherKey="ClassID" Type="Class" IsForeignKey="true" />
      <Association Name="User_LeaderFollower" Member="Leader" ThisKey="LeaderID" OtherKey="UserID" Type="User" IsForeignKey="true" />
      <Association Name="User_LeaderFollower1" Member="Follower" ThisKey="FollowerID" OtherKey="UserID" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.uspGet_All_TransActionsByUser" Method="uspGet_All_TransActionsByUser">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="uspGet_All_TransActionsByUserResult">
      <Column Name="TransactionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="RecieverName" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TransactionDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TransactionType" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_Get_User_points" Method="usp_Get_User_points">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Points" Parameter="points" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_Add_New_Transaction" Method="usp_Add_New_Transaction">
    <Parameter Name="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RecUserName" Parameter="recUserName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Amount" Parameter="amount" Type="System.Double" DbType="Float" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="TransactionDate" Parameter="transactionDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="TransactionType" Parameter="transactionType" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_Get_User_List_Order_By_Performance_For_Class" Method="usp_Get_User_List_Order_By_Performance_For_Class">
    <Parameter Name="ClassID" Parameter="classID" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_Get_User_List_Order_By_Performance_For_ClassResult">
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Position" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FollowerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>